[package]
name = "aura_api_client"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4" }
fastnum = { version = "0.7.4", optional = true }
solana-address = { version = "2" }
solana-instruction-error = { version = "2", optional = true }
solana-keypair = { version = "3", optional = true }
solana-signature = { version = "3" }
solana-transaction-error = { version = "3", features = ["serde"], optional = true }

decisol = { git = "https://github.com/4r33x/decisol", features = ["proto"] }
inventory = { version = "0.3", optional = true }
log = "0.4"
nohash-hasher = { version = "0.2.0", optional = true }
proto_rs = { version = "0.11.26", default-features = false, features = [
  "chrono",
  "fastnum",
  "solana",
  "stable"
], optional = true }
serde = { version = "1", features = ["derive"], optional = true }
tonic = { version = "0.14.6", optional = true, default-features = false, features = ["codegen"] }

[features]
default = ["client"]
build-schemas = [
  "decisol/build-schemas",
  "dep:inventory",
  "proto_rs/build-schemas"
]
api-types = [
  "chrono/serde",
  "dep:fastnum",
  "dep:proto_rs",
  "dep:serde",
  "dep:solana-instruction-error",
  "dep:solana-keypair",
  "dep:solana-transaction-error",
  "dep:teloxide-core",
  "solana-address/serde",
  "solana-signature/serde"
]
client-generic = [
  "api-types",
  "dep:nohash-hasher",
  "dep:tonic",
  "proto_rs/tonic"
]
client = [
  "client-generic",
  "proto_rs/tonic-transport",
  "tonic/transport"
]
dev = []
private_client = ["client"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
proto_rs = { version = "0.11.26", default-features = false, features = ["teloxide"], optional = true }
teloxide-core = { version = "0.13", optional = true, default-features = false }
